name: Build Android Release
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          pakager: npm

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build APK
        run: eas build --platform android --profile preview --non-interactive --local --output=./app-release.apk

      - name: 📎 Upload APK to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}