name: Build Android Release
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Mis à jour de 18 à 20 pour supporter eas-cli 18.3.0+

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build APK
        # Ajout de l'installation de sharp-cli si nécessaire pour la gestion des icônes en local
        run: |
          npx expo prebuild
          eas build --platform android --profile preview --non-interactive --local --output=./app-release.apk
          
      - name: 💾 Save APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ./app-release.apk

      - name: 📎 Upload APK to Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'release' # S'assure que l'upload ne tourne que lors d'une release
        with:
          files: ./app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}